version: '2.1'

services:
  airflow-dev-env:
    image: marcusrehm/airflow-dev-env
    env_file:
      - .env
    build: .
      args:
        AIRFLOW_VERSION: 1.9
        AIRFLOW_HOME: /usr/local/airflow
    ports:
      - 8080:8080
    volumes:
      - /home/marcus/airflow/lib/:/usr/local/airflow/lib:rw
      - /home/marcus/airflow/plugins/:/usr/local/airflow/lib:rw
      - /home/marcus/airflow/dags/:/usr/local/airflow/dags:rw
      - /home/marcus/airflow/db/:/usr/local/airflow/db:rw